import type { OrderBO } from '@/types/order/OrderBO.ts';
import { KitchenStatusENUM } from '@/types/order/KitchenStatusENUM.ts';
import { OrderStatusENUM } from '@/types/order/OrderStatusENUM.ts';
import { PaymentMethodENUM } from '@/types/order/PaymentMethodENUM.ts';
import { PaymentStatusENUM } from '@/types/order/PaymentStatusENUM.ts';

export const ordersData: OrderBO[] = [
  {
    id: 'ord-001',
    orderNumber: 'ROM-001',
    tableNumber: 'T3',
    customerName: 'Ananya Krishnan',
    customerPhone: '9876543210',
    customerEmail: 'ananya@example.com',
    items: [
      {
        menuItemId: 'tea-004',
        name: 'Butterfly Pea Bloom',
        image: 'https://images.unsplash.com/photo-1563822249366-3efb23b8e0c9?w=600&q=80',
        quantity: 2,
        unitPrice: 320,
        totalPrice: 640,
      },
      {
        menuItemId: 'frappe-001',
        name: 'Classic Coffee Frappe',
        image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80',
        variant: 'Large',
        quantity: 1,
        unitPrice: 340,
        totalPrice: 340,
      },
    ],
    subtotal: 980,
    tax: 49,
    total: 1029,
    paymentMethod: PaymentMethodENUM.PHONEPE,
    paymentStatus: PaymentStatusENUM.PAID,
    orderStatus: OrderStatusENUM.CONFIRMED,
    kitchenStatus: KitchenStatusENUM.PREPARING,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'ord-002',
    orderNumber: 'ROM-002',
    tableNumber: 'T7',
    customerName: 'Siddharth Rao',
    customerPhone: '9765432109',
    items: [
      {
        menuItemId: 'coldbrew-001',
        name: 'Signature Cold Brew',
        image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80',
        variant: 'Large 380ml',
        quantity: 2,
        unitPrice: 320,
        totalPrice: 640,
      },
      {
        menuItemId: 'beans-001',
        name: 'Soroco House Blend',
        image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&q=80',
        variant: '250g',
        quantity: 1,
        unitPrice: 680,
        totalPrice: 680,
      },
    ],
    subtotal: 1320,
    tax: 66,
    total: 1386,
    paymentMethod: PaymentMethodENUM.RAZORPAY,
    paymentStatus: PaymentStatusENUM.PAID,
    orderStatus: OrderStatusENUM.CONFIRMED,
    kitchenStatus: KitchenStatusENUM.PREPARED,
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'ord-003',
    orderNumber: 'ROM-003',
    tableNumber: 'T12',
    customerName: 'Meera Iyer',
    customerPhone: '9654321098',
    items: [
      {
        menuItemId: 'noncoffee-001',
        name: 'Jasmine White Latte',
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80',
        variant: 'Iced',
        quantity: 1,
        unitPrice: 300,
        totalPrice: 300,
      },
      {
        menuItemId: 'frappe-003',
        name: 'Caramelous Frappe',
        image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&q=80',
        variant: 'Regular',
        quantity: 1,
        unitPrice: 320,
        totalPrice: 320,
      },
      {
        menuItemId: 'tea-001',
        name: 'Darjeeling First Flush',
        image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80',
        quantity: 1,
        unitPrice: 280,
        totalPrice: 280,
      },
    ],
    subtotal: 900,
    tax: 45,
    total: 945,
    paymentMethod: PaymentMethodENUM.PHONEPE,
    paymentStatus: PaymentStatusENUM.PENDING,
    orderStatus: OrderStatusENUM.PENDING,
    kitchenStatus: KitchenStatusENUM.IN_QUEUE,
    createdAt: new Date(Date.now() - 3 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60000).toISOString(),
  },
  {
    id: 'ord-004',
    orderNumber: 'ROM-004',
    tableNumber: 'T2',
    customerName: 'Rohan Desai',
    customerPhone: '9543210987',
    items: [
      {
        menuItemId: 'filter-001',
        name: 'The Brewing Edge',
        image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80',
        variant: 'Large',
        quantity: 3,
        unitPrice: 220,
        totalPrice: 660,
      },
    ],
    subtotal: 660,
    tax: 33,
    total: 693,
    paymentMethod: PaymentMethodENUM.CASH,
    paymentStatus: PaymentStatusENUM.PAID,
    orderStatus: OrderStatusENUM.COMPLETED,
    kitchenStatus: KitchenStatusENUM.DELIVERED,
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 'ord-005',
    orderNumber: 'ROM-005',
    tableNumber: 'T5',
    customerName: 'Divya Patel',
    customerPhone: '9432109876',
    items: [
      {
        menuItemId: 'frappe-005',
        name: 'Brown Butter Frappe',
        image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80',
        variant: 'Large',
        quantity: 2,
        unitPrice: 400,
        totalPrice: 800,
      },
      {
        menuItemId: 'noncoffee-004',
        name: 'Flower Tea',
        image: 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=600&q=80',
        quantity: 1,
        unitPrice: 320,
        totalPrice: 320,
      },
    ],
    subtotal: 1120,
    tax: 56,
    total: 1176,
    paymentMethod: PaymentMethodENUM.RAZORPAY,
    paymentStatus: PaymentStatusENUM.PAID,
    orderStatus: OrderStatusENUM.CONFIRMED,
    kitchenStatus: KitchenStatusENUM.IN_QUEUE,
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
  },
];
